### ISSUE TITLE
Student Skills Checklist

### ISSUE THREAD

**Issue by martijorbam** [martijorbam/marti_2025#1]
- [x] Laptop Verification or Cloud Workspace
Rank: 4
Notes: verification by Linux commands notebook
 
- [x] VSCode
Rank: 4
Notes: live change code, commit, make, run localhost, test, debug

- [x] Show VSCode GitLens
Rank: 3
Notes: verify commits, show change, comments, reset to commit, run on old commit
 
- [x] GitHub cloud repo
Rank: 4
Notes: live push change, verify id, review profile

- [x] GitHub Pages Actions
Rank: 4
Notes: review runs and verify runtime, receive demo

- [x] Hacks Tools & Equipment Play
Rank: 4
Notes:

- [x] Hacks GitHub Pages Playground
Rank: 4
Notes:

- [x] Hacks SASS Basics
Rank: 4
Notes:

- [x] Hacks Jupyter Notebook
Rank: 3
Notes:

- [x] Pair Programming
Rank: 2
Notes: tangibles that show co-operative work

**Comment by GavinCopley** [comment]
- [x] Laptop Verification or Cloud Workspace
Rank: 4
Notes: verification by Linux commands notebook

- [x] VSCode
Rank: 4
Notes: live change code, commit, make, run localhost, test, debug

- [x] Show VSCode GitLens
Rank: 3
Notes: verify commits, show change, comments, reset to commit, run on old commit

- [x] GitHub cloud repo
Rank: 4
Notes: live push change, verify id, review profile

- [x] GitHub Pages Actions
Rank: 2
Notes: review runs and verify runtime, receive demo

- [x] Hacks Tools & Equipment Play
Rank: 4
Notes:

- [x] Hacks GitHub Pages Playground
Rank: 4
Notes:

- [x] Hacks SASS Basics
Rank: 4
Notes:

- [x] Hacks Jupyter Notebook
Rank: 4
Notes:

- [x] Pair Programming
Rank: 1
Notes: tangibles that show co-operative work

**Comment by GavinCopley** [comment]
Grader Skills Worksheet

- [x] Attendance
Rank: 4
Notes:

- [x] Work Habits
Rank: 4
Notes:

- [x] Behavior
Rank: 4
Notes:

- [x] Timeliness
Rank: 3
Notes:

- [x] Tech Sense
Rank: 3
Notes:

- [x] Tech Talk
Rank: 4
Notes:

- [x] Tech Growth
Rank: 4
Notes:

- [x] Advocacy
Rank: 4
Notes:

- [x] Comm & Collab
Rank: 3
Notes:

- [x] Integrity
Rank: 4
Notes:

- [x] Organized
Rank: 3
Notes:

**Comment by GyutaeKim1** [comment]
- [x] Laptop Verification or Cloud Workspace
Rank: 4
Notes: verification by Linux commands notebook

- [x] VSCode
Rank: 4
Notes: live change code, commit, make, run localhost, test, debug

- [x]  Show VSCode GitLens
Rank: 2
Notes: verify commits, show change, comments, reset to commit, run on old commit

- [x] GitHub cloud repo
Rank: 4
Notes: live push change, verify id, review profile

- [x] GitHub Pages Actions
Rank: 3
Notes: review runs and verify runtime, receive demo

- [x] Hacks Tools & Equipment Play
Rank: 4
Notes:
 

- [x] Hacks GitHub Pages Playground
Rank: 4
Notes:

- [x] Hacks SASS Basics
Rank: 3
Notes:

- [x]  Hacks Jupyter Notebook
Rank: 4
Notes:

- [x] Pair Programming
Rank: 1
Notes: tangibles that show co-operative work

**Comment by GyutaeKim1** [comment]
Grader Skills Worksheet

- [x] Attendance
Rank: 4
Notes:

- [x] Work Habits
Rank: 4
Notes:

 

- [x] Behavior
Rank: 4
Notes:

- [x] Timeliness
Rank: 3
Notes:

- [x] Tech Sense
Rank: 3
Notes:

- [x] Tech Talk
Rank: 3
Notes:

- [x] Tech Growth
Rank: 4
Notes:

 

- [x] Advocacy
Rank: 4
Notes:

 

- [x] Comm & Collab
Rank: 4
Notes:

 

- [x] Integrity
Rank: 4
Notes:

- [x] Organized
Rank: 3
Notes:
